

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "compagnyName": "solution  Gmbh",
  "compagnyCode": "solus",
  "email": "contact@solus.com",
  "adminFullName": "koeFoe",
  "adminEmail": "koe@solus.com",
  "adminUserName": "koefoe",
  "adminPassword": "password123"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "koefoe",
  "password": "password123"
}
###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password123"
}




###
GET http://localhost:8080/api/v1/users/f1e2d3c4-b5a6-7890-abcd-ef1234567890
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIgZjFlMmQzYzQtYjVhNi03ODkwLWFiY2QtZWYxMjM0NTY3ODkwICIsInJvbGUiOiJST0xFX0NPTVBBR05ZX0FETUlOIiwiaWF0IjoxNzc5ODIyNzIyLCJleHAiOjE3Nzk5MDk1MjJ9.V2sx1eQw4htv0XRFS8cpbytEydJJrVpm4dPZ7HT_Wbip1FMRbWr5inCctt9j1zseCqqriBjBXN-AlyOkWPVNvBCwFtA37IBkjpkbe1Nut-aiG87dow6cb1n_q0gR13fcELHqFzfek9cNO229b0NO5gNqoC5JYLKliSMthejwA7OTGL_DbVnlMru8l4BfLo8VAXaifxr6xE1kw0Q3jig2c-Um0O9t0i7m42yESlvc5Z4VEp_YI-znX7ibfJIfAQ134XnF7bQWelOqgkYzosJwoTLhxv91Zt3pJrzh-34klBCGVEVM5nSf4IJOg1PLYyrMVjuBDGzYrB5DR4i804P6Ig

