

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "compagnyName": "solution  Gmbh",
  "compagnyCode": "solus",
  "email": "contact@solus.com",
  "adminFullName": "koeFoe",
  "adminEmail": "koe@solus.com",
  "adminUserName": "koefoe",
  "adminPassword": "password123"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "koefoe",
  "password": "password123"
}

###
POST http://localhost:8080/api/v1/tenants/approve/420a65d5-a47f-4bb0-8363-72772e33f4cb