/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryRequest } from './models/category-request';
export type { CategoryResponse } from './models/category-response';
export type { ErrorDto } from './models/error-dto';
export type { LoginReponse } from './models/login-reponse';
export type { LoginRequest } from './models/login-request';
export type { PageReponse } from './models/page-reponse';
export type { PageReponseCategoryResponse } from './models/page-reponse-category-response';
export type { PageReponseProductResponse } from './models/page-reponse-product-response';
export type { PageReponseStockMvtResponse } from './models/page-reponse-stock-mvt-response';
export type { PageReponseUserResponse } from './models/page-reponse-user-response';
export type { ProductRequest } from './models/product-request';
export type { ProductResponse } from './models/product-response';
export type { RegisterTenantRequest } from './models/register-tenant-request';
export type { StockMvtRequest } from './models/stock-mvt-request';
export type { StockMvtResponse } from './models/stock-mvt-response';
export type { UserRequest } from './models/user-request';
export type { UserResponse } from './models/user-response';
