/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockMvtResponse } from '../../models/stock-mvt-response';

export interface GetStockMvtById$Params {
  'stock-mvt-id': string;
}

export function getStockMvtById(http: HttpClient, rootUrl: string, params: GetStockMvtById$Params, context?: HttpContext): Observable<StrictHttpResponse<StockMvtResponse>> {
  const rb = new RequestBuilder(rootUrl, getStockMvtById.PATH, 'get');
  if (params) {
    rb.path('stock-mvt-id', params['stock-mvt-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockMvtResponse>;
    })
  );
}

getStockMvtById.PATH = '/api/v1/stock-mvts/{stock-mvt-id}';
