/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activateTenant } from '../fn/tenant-controller/activate-tenant';
import { ActivateTenant$Params } from '../fn/tenant-controller/activate-tenant';
import { approveTenant } from '../fn/tenant-controller/approve-tenant';
import { ApproveTenant$Params } from '../fn/tenant-controller/approve-tenant';
import { deactivateTenant } from '../fn/tenant-controller/deactivate-tenant';
import { DeactivateTenant$Params } from '../fn/tenant-controller/deactivate-tenant';
import { findAllTenants } from '../fn/tenant-controller/find-all-tenants';
import { FindAllTenants$Params } from '../fn/tenant-controller/find-all-tenants';
import { PageReponse } from '../models/page-reponse';
import { suspendTenant } from '../fn/tenant-controller/suspend-tenant';
import { SuspendTenant$Params } from '../fn/tenant-controller/suspend-tenant';

@Injectable({ providedIn: 'root' })
export class TenantControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `approveTenant()` */
  static readonly ApproveTenantPath = '/api/v1/tenants/approve/{tenant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveTenant$Response(params: ApproveTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = approveTenant(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveTenant(params: ApproveTenant$Params, context?: HttpContext): Observable<void> {
    const resp = this.approveTenant$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `suspendTenant()` */
  static readonly SuspendTenantPath = '/api/v1/tenants/suspend/{tenant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `suspendTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  suspendTenant$Response(params: SuspendTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = suspendTenant(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `suspendTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  suspendTenant(params: SuspendTenant$Params, context?: HttpContext): Observable<void> {
    const resp = this.suspendTenant$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deactivateTenant()` */
  static readonly DeactivateTenantPath = '/api/v1/tenants/deactivate/{tenant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deactivateTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  deactivateTenant$Response(params: DeactivateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deactivateTenant(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deactivateTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deactivateTenant(params: DeactivateTenant$Params, context?: HttpContext): Observable<void> {
    const resp = this.deactivateTenant$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `activateTenant()` */
  static readonly ActivateTenantPath = '/api/v1/tenants/activate/{tenant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activateTenant()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateTenant$Response(params: ActivateTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = activateTenant(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activateTenant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateTenant(params: ActivateTenant$Params, context?: HttpContext): Observable<void> {
    const resp = this.activateTenant$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllTenants()` */
  static readonly FindAllTenantsPath = '/api/v1/tenants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllTenants()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTenants$Response(params?: FindAllTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReponse>> {
    const obs = findAllTenants(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllTenants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTenants(params?: FindAllTenants$Params, context?: HttpContext): Observable<PageReponse> {
    const resp = this.findAllTenants$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageReponse>): PageReponse => r.body)
    );
  }

}
