/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoryResponse } from '../models/category-response';
import { createCategory } from '../fn/ui-category-controllers/create-category';
import { CreateCategory$Params } from '../fn/ui-category-controllers/create-category';
import { deleteCategory } from '../fn/ui-category-controllers/delete-category';
import { DeleteCategory$Params } from '../fn/ui-category-controllers/delete-category';
import { getAllCategories } from '../fn/ui-category-controllers/get-all-categories';
import { GetAllCategories$Params } from '../fn/ui-category-controllers/get-all-categories';
import { getCategoryById1 } from '../fn/ui-category-controllers/get-category-by-id-1';
import { GetCategoryById1$Params } from '../fn/ui-category-controllers/get-category-by-id-1';
import { PageReponseCategoryResponse } from '../models/page-reponse-category-response';
import { updateCategory } from '../fn/ui-category-controllers/update-category';
import { UpdateCategory$Params } from '../fn/ui-category-controllers/update-category';


/**
 * Endpoints for managing categories
 */
@Injectable({ providedIn: 'root' })
export class UiCategoryControllersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCategoryById1()` */
  static readonly GetCategoryById1Path = '/api/v1/categories/{category-id}';

  /**
   * Get Category By Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById1$Response(params: GetCategoryById1$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
    const obs = getCategoryById1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Category By Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById1(params: GetCategoryById1$Params, context?: HttpContext): Observable<CategoryResponse> {
    const resp = this.getCategoryById1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body)
    );
  }

  /** Path part for operation `updateCategory()` */
  static readonly UpdateCategoryPath = '/api/v1/categories/{category-id}';

  /**
   * Update Category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateCategory$Response(params: UpdateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateCategory(params: UpdateCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteCategory()` */
  static readonly DeleteCategoryPath = '/api/v1/categories/{category-id}';

  /**
   * Delete Category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory$Response(params: DeleteCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Delete Category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory(params: DeleteCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllCategories()` */
  static readonly GetAllCategoriesPath = '/api/v1/categories';

  /**
   * Get all Categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCategories$Response(params?: GetAllCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReponseCategoryResponse>> {
    const obs = getAllCategories(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get all Categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCategories(params?: GetAllCategories$Params, context?: HttpContext): Observable<PageReponseCategoryResponse> {
    const resp = this.getAllCategories$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageReponseCategoryResponse>): PageReponseCategoryResponse => r.body)
    );
  }

  /** Path part for operation `createCategory()` */
  static readonly CreateCategoryPath = '/api/v1/categories';

  /**
   * Create Category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory$Response(params: CreateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory(params: CreateCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.createCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
