/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProduct } from '../fn/ui-product-controllers/create-product';
import { CreateProduct$Params } from '../fn/ui-product-controllers/create-product';
import { deleteProduct } from '../fn/ui-product-controllers/delete-product';
import { DeleteProduct$Params } from '../fn/ui-product-controllers/delete-product';
import { getAllProducts } from '../fn/ui-product-controllers/get-all-products';
import { GetAllProducts$Params } from '../fn/ui-product-controllers/get-all-products';
import { getCategoryById } from '../fn/ui-product-controllers/get-category-by-id';
import { GetCategoryById$Params } from '../fn/ui-product-controllers/get-category-by-id';
import { PageReponseProductResponse } from '../models/page-reponse-product-response';
import { ProductResponse } from '../models/product-response';
import { updateProduct } from '../fn/ui-product-controllers/update-product';
import { UpdateProduct$Params } from '../fn/ui-product-controllers/update-product';


/**
 * Endpoints for managing products
 */
@Injectable({ providedIn: 'root' })
export class UiProductControllersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCategoryById()` */
  static readonly GetCategoryByIdPath = '/api/v1/products/{product-id}';

  /**
   * Get Product By Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById$Response(params: GetCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    const obs = getCategoryById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get Product By Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById(params: GetCategoryById$Params, context?: HttpContext): Observable<ProductResponse> {
    const resp = this.getCategoryById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `updateProduct()` */
  static readonly UpdateProductPath = '/api/v1/products/{product-id}';

  /**
   * Update Product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateProduct$Response(params: UpdateProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateProduct(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update Product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateProduct(params: UpdateProduct$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateProduct$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteProduct()` */
  static readonly DeleteProductPath = '/api/v1/products/{product-id}';

  /**
   * Delete Product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProduct$Response(params: DeleteProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteProduct(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Delete Product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProduct(params: DeleteProduct$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteProduct$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllProducts()` */
  static readonly GetAllProductsPath = '/api/v1/products';

  /**
   * Get all Products.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProducts$Response(params?: GetAllProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReponseProductResponse>> {
    const obs = getAllProducts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get all Products.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProducts(params?: GetAllProducts$Params, context?: HttpContext): Observable<PageReponseProductResponse> {
    const resp = this.getAllProducts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageReponseProductResponse>): PageReponseProductResponse => r.body)
    );
  }

  /** Path part for operation `createProduct()` */
  static readonly CreateProductPath = '/api/v1/products';

  /**
   * Create Product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProduct()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct$Response(params: CreateProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createProduct(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create Product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProduct$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct(params: CreateProduct$Params, context?: HttpContext): Observable<void> {
    const resp = this.createProduct$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
