/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createStockMvt } from '../fn/ui-stock-movement-controllers/create-stock-mvt';
import { CreateStockMvt$Params } from '../fn/ui-stock-movement-controllers/create-stock-mvt';
import { deleteStockMvt } from '../fn/ui-stock-movement-controllers/delete-stock-mvt';
import { DeleteStockMvt$Params } from '../fn/ui-stock-movement-controllers/delete-stock-mvt';
import { getAllStckMvts } from '../fn/ui-stock-movement-controllers/get-all-stck-mvts';
import { GetAllStckMvts$Params } from '../fn/ui-stock-movement-controllers/get-all-stck-mvts';
import { getStockMvtById } from '../fn/ui-stock-movement-controllers/get-stock-mvt-by-id';
import { GetStockMvtById$Params } from '../fn/ui-stock-movement-controllers/get-stock-mvt-by-id';
import { PageReponseStockMvtResponse } from '../models/page-reponse-stock-mvt-response';
import { StockMvtResponse } from '../models/stock-mvt-response';
import { updateStockMvt } from '../fn/ui-stock-movement-controllers/update-stock-mvt';
import { UpdateStockMvt$Params } from '../fn/ui-stock-movement-controllers/update-stock-mvt';


/**
 * Endpoints for managing stock movements
 */
@Injectable({ providedIn: 'root' })
export class UiStockMovementControllersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getStockMvtById()` */
  static readonly GetStockMvtByIdPath = '/api/v1/stock-mvts/{stock-mvt-id}';

  /**
   * Get stock movement By Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStockMvtById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStockMvtById$Response(params: GetStockMvtById$Params, context?: HttpContext): Observable<StrictHttpResponse<StockMvtResponse>> {
    const obs = getStockMvtById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get stock movement By Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStockMvtById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStockMvtById(params: GetStockMvtById$Params, context?: HttpContext): Observable<StockMvtResponse> {
    const resp = this.getStockMvtById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockMvtResponse>): StockMvtResponse => r.body)
    );
  }

  /** Path part for operation `updateStockMvt()` */
  static readonly UpdateStockMvtPath = '/api/v1/stock-mvts/{stock-mvt-id}';

  /**
   * Update stock movement.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStockMvt()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateStockMvt$Response(params: UpdateStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update stock movement.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStockMvt$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateStockMvt(params: UpdateStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteStockMvt()` */
  static readonly DeleteStockMvtPath = '/api/v1/stock-mvts/{stock-mvt-id}';

  /**
   * Delete stock movements.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStockMvt()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStockMvt$Response(params: DeleteStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Delete stock movements.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStockMvt$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStockMvt(params: DeleteStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllStckMvts()` */
  static readonly GetAllStckMvtsPath = '/api/v1/stock-mvts';

  /**
   * Get all stock movements.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStckMvts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStckMvts$Response(params?: GetAllStckMvts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReponseStockMvtResponse>> {
    const obs = getAllStckMvts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get all stock movements.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStckMvts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStckMvts(params?: GetAllStckMvts$Params, context?: HttpContext): Observable<PageReponseStockMvtResponse> {
    const resp = this.getAllStckMvts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageReponseStockMvtResponse>): PageReponseStockMvtResponse => r.body)
    );
  }

  /** Path part for operation `createStockMvt()` */
  static readonly CreateStockMvtPath = '/api/v1/stock-mvts';

  /**
   * Create stock movement.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createStockMvt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStockMvt$Response(params: CreateStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Create stock movement.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createStockMvt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStockMvt(params: CreateStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.createStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
