/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PageReponse {
  content?: Array<any>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
