/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface PageReponseUserResponse {
  content?: Array<UserResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
