/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterTenantRequest {
  adminEmail: string;
  adminFullName: string;
  adminPassword: string;
  adminUserName: string;
  compagnyCode: string;
  compagnyName: string;
  email: string;
}
