/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockMvtRequest {
  comment?: string;
  mvtDate: string;
  productId: string;
  quantity: number;
  typeMvt: 'IN' | 'OUT';
}
